[project]
name = "chzzkchat"
version = "0.1.0"
description = "A Python library for Chzzk chat interactions."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.5",
    "websocket-client>=1.8.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.11",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88
target-version = "py310"
select = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"