[project]
name = "chzzkchat"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "click>=8.2.1",
    "requests>=2.32.3",
    "websocket-client>=1.8.0",
]


[dependency-groups]
dev = [
    "ruff>=0.11.11",
]

[tool.ruff]
line-length = 88 
target-version = "py310"
select = ["ALL"] 
ignore = [
    "E501",  # Line too long
    "D",  # Docstring not found
]

[tool.uv]
package = true

[project.scripts]
chzzkchat = "chzzkchat.cli:cli"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["chzzkchat*"]
